title: Fund Law Group
baseurl: /
permalink: '/:title/'
palette: green
header:
  title: Fund Law Group
  logo_img: images/logo.png
  has_nav: true
  menu:
    actions:
      - label: Contact Us
        url: /contact
footer:
  logo_img: images/logo.png
  tagline: Law Firm for Fund Organizers
  has_nav: true
  nav_title: Firm
  has_social: true
  social_title: Follow Us
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: '&copy; Fund Law Group LLP. All rights reserved.'
  links:
    - text: Fund Law Group
      url: 'https://www.fundlawgroup.com'
      new_window: false
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
